apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-deployment-conf
  labels:
    app: otel-collector-deployment-conf
    component: otel-collector-deployment-conf
data:
  otel-deployment-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
        send_batch_max_size: 10
        send_batch_size: 2
        timeout: 30s
    exporters:
      logging:
        loglevel: debug
      dynatrace:
        prefix: otel
        timeout: 30s
        default_dimensions:
          dimension_example: dimension_value
        endpoint: "https://bvl56529.live.dynatrace.com/api/v2/metrics/ingest"
        api_token: "<redacted>"
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 120s
        sending_queue:
          enabled: true
          num_consumers: 10
          queue_size: 5000
      prometheusremotewrite:
        endpoint: https://560265:<redacted>@prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [dynatrace,prometheusremotewrite,logging]
